Posting new code from Jingjing Li for the Batch .NET quickstart
Azure-Samples/batch-dotnet-quickstart pull request #18
Opened 2023-04-29 00:51 UTC by v-thepet

## Purpose

Updated code for the Batch .NET quickstart https://learn.microsoft.com/azure/batch/quick-run-dotnet

## Does this introduce a breaking change?

```
[ ] Yes
[x ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?
Updated C# app

```
[x ] Bugfix (GitHub issue)
[ ] Feature
[x ] Code style update (formatting, local variables)
[x ] Refactoring (no functional changes, no api changes)
[x ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Build and run the program

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2023-04-29 01:06 UTC, v-thepet commented
#sign-off - whoever can merge thank you to clear GitHub issue https://github.com/MicrosoftDocs/azure-docs/issues/92899

2023-04-29 01:20 UTC, Padmalathas approved these changes

2023-04-29 01:34 UTC, Padmalathas commented
#sign-off

2023-04-29 01:36 UTC, Padmalathas commented
@dlepow, Request you to please approve the changes so that its auto-merged to the repo. Thanks!

2023-05-01 15:04 UTC, dpwatrous requested changes
This looks really good overall, just a few minor comments.

2023-05-01 15:04 UTC, dpwatrous commented on README.md
> +- Visual Studio 2019, or [.NET Core 6.0](https://www.microsoft.com/net/download/dotnet) for Linux or Windows
Should we make this "Visual Studio 2019 or higher" and ".NET 6.0 or higher"? (.NET 6 is no longer called ".NET Core")

2023-05-01 18:47 UTC, v-thepet commented on BatchDotnetQuickstart/Program.cs
> +                Console.WriteLine(@"BlobClient must be authorized with Shared Key
@dpwatrous How is this? Please request any changes or merge if ok! Thanks

2023-05-01 18:49 UTC, v-thepet commented
@dpwatrous Please critique the try catch block I have added and let me know any further changes or please merge if ok! Thanks
@Padmalathas FYI

2023-05-01 19:03 UTC, dpwatrous approved these changes
The changes look good to me - thanks for the quick update! I'll go ahead and merge it.

2023-05-01 19:04 UTC, merged